name: senpie
description: "Senpie - A mobile anime tracking and downloading application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # Networking
  dio: ^5.4.0
  http: ^1.1.2

  # HTML Parsing
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0

  # Download Management
  flutter_downloader: ^1.11.6
  dio_smart_retry: ^6.0.0

  # Background Processing
  workmanager: ^0.5.2
  wakelock_plus: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  sqflite: ^2.3.0

  # File Management
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  share_plus: ^7.2.2

  # FFmpeg for HLS streams
  ffmpeg_kit_flutter: ^6.0.3

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3

  # Notifications
  flutter_local_notifications: ^16.3.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

